interface ReportData {
  predictions: any[];
  currentPrediction: any;
  insights: any[];
  generatedAt: string;
}

export async function generatePDFReport(data: ReportData): Promise<void> {
  // Create HTML content for the report
  const reportContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>AgriPredict Analysis Report</title>
      <style>
        body { font-family: Arial, sans-serif; margin: 20px; color: #333; }
        .header { text-align: center; margin-bottom: 30px; padding-bottom: 20px; border-bottom: 2px solid #16a34a; }
        .section { margin-bottom: 25px; }
        .metric { display: inline-block; margin: 10px; padding: 15px; background: #f3f4f6; border-radius: 8px; }
        .metric h3 { margin: 0; color: #16a34a; }
        .metric p { margin: 5px 0 0 0; font-size: 24px; font-weight: bold; }
        .recommendation { background: #ecfdf5; padding: 15px; margin: 10px 0; border-left: 4px solid #16a34a; }
        .footer { margin-top: 30px; text-align: center; font-size: 12px; color: #666; }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>🌾 AgriPredict Analysis Report</h1>
        <p>Generated on ${new Date(data.generatedAt).toLocaleDateString()}</p>
      </div>

      ${data.currentPrediction ? `
        <div class="section">
          <h2>Current Prediction Summary</h2>
          <div class="metric">
            <h3>Predicted Yield</h3>
            <p>${data.currentPrediction.predictedYield.toFixed(1)} t/ha</p>
          </div>
          <div class="metric">
            <h3>Crop Type</h3>
            <p>${data.currentPrediction.crop}</p>
          </div>
          <div class="metric">
            <h3>Season</h3>
            <p>${data.currentPrediction.season}</p>
          </div>
          <div class="metric">
            <h3>Location</h3>
            <p>${data.currentPrediction.location}</p>
          </div>
          ${data.currentPrediction.energyData ? `
            <div class="metric">
              <h3>Energy Efficiency</h3>
              <p>${data.currentPrediction.energyData.efficiencyScore.toFixed(1)} kg/kWh</p>
            </div>
          ` : ''}
        </div>
      ` : ''}

      <div class="section">
        <h2>Key Recommendations</h2>
        <div class="recommendation">
          <h4>🔋 Energy Optimization</h4>
          <p>Switch to solar irrigation to improve efficiency by 35% and reduce costs by $120/ha annually.</p>
        </div>
        <div class="recommendation">
          <h4>🌱 Yield Enhancement</h4>
          <p>Implement precision fertilizer application to increase yield by 12% while reducing fertilizer use.</p>
        </div>
        <div class="recommendation">
          <h4>🌍 Sustainability</h4>
          <p>Adopt cover crops and no-till practices to reduce CO₂ emissions by 25%.</p>
        </div>
      </div>

      ${data.predictions.length > 0 ? `
        <div class="section">
          <h2>Historical Predictions</h2>
          <table style="width: 100%; border-collapse: collapse;">
            <tr style="background: #f3f4f6;">
              <th style="padding: 10px; text-align: left; border: 1px solid #d1d5db;">Crop</th>
              <th style="padding: 10px; text-align: left; border: 1px solid #d1d5db;">Location</th>
              <th style="padding: 10px; text-align: left; border: 1px solid #d1d5db;">Season</th>
              <th style="padding: 10px; text-align: left; border: 1px solid #d1d5db;">Yield (t/ha)</th>
            </tr>
            ${data.predictions.slice(-5).map(p => `
              <tr>
                <td style="padding: 10px; border: 1px solid #d1d5db;">${p.crop}</td>
                <td style="padding: 10px; border: 1px solid #d1d5db;">${p.location}</td>
                <td style="padding: 10px; border: 1px solid #d1d5db;">${p.season}</td>
                <td style="padding: 10px; border: 1px solid #d1d5db;">${p.predictedYield.toFixed(1)}</td>
              </tr>
            `).join('')}
          </table>
        </div>
      ` : ''}

      <div class="footer">
        <p>This report was generated by AgriPredict AI-Powered Agricultural Intelligence Platform</p>
        <p>For questions or support, contact: support@agripredict.com</p>
      </div>
    </body>
    </html>
  `;

  // Create and download the HTML file (as PDF generation requires server-side processing)
  const blob = new Blob([reportContent], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `agripredict-report-${new Date().toISOString().split('T')[0]}.html`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);

  // Show success message
  alert('Report downloaded successfully! Open the HTML file in your browser and use "Print to PDF" to create a PDF version.');
}